# Generated by Django 5.1.3 on 2024-11-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original_bd/')),
                ('result_image', models.ImageField(upload_to='result_bd/')),
                ('model_weight', models.FileField(upload_to='weights/')),
                ('is_grayscale', models.BooleanField(default=False)),
                ('contour_size', models.IntegerField(default=3)),
                ('rgb', models.CharField(max_length=11)),
            ],
        ),
    ]
